name = input("Give me your admin name: ")
ID = input("Enter your DOB :")
age = input("Enter your age :")
role = input("Enter your role :")

print(f"\nAdmin User")
print(f"name: {name}")
print(f"ID: {ID}")
print(f"age: {age}")
print(f"role: {role}")